name: s3 Static Webpage (HTML)
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code 
        uses: actions/checkout@v4
      - name: configure Aws 
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-access-key-key: ${{ secrets.AWS_ACCESS_KEY_KEY }}
          aws-region: ap-south-1
          
          
